"use client";

import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import Link from "next/link";
import { ArrowLeft, Copy, Download, Printer } from "lucide-react";
import toast from "react-hot-toast";
import { DoctorSummary } from "@/types";

export default function DoctorSummaryViewPage() {
  const params = useParams();
  const supabase = createClient();
  const [summary, setSummary] = useState<DoctorSummary | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    supabase
      .from("doctor_summaries")
      .select("*, family_members(full_name)")
      .eq("id", params.id)
      .single()
      .then(({ data }) => {
        setSummary(data as DoctorSummary);
        setLoading(false);
      });
  }, [params.id]);

  function handleCopy() {
    if (summary?.generated_summary) {
      navigator.clipboard.writeText(summary.generated_summary);
      toast.success("Copied to clipboard!");
    }
  }

  function handlePrint() {
    window.print();
  }

  async function handleDownloadPDF() {
    // Dynamically import jspdf to avoid SSR issues
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF();
    doc.setFontSize(11);
    const lines = doc.splitTextToSize(summary?.generated_summary || "", 180);
    doc.text(lines, 15, 20);
    doc.save(`doctor-summary-${params.id}.pdf`);
    toast.success("PDF downloaded!");
  }

  if (loading) return (
    <div className="flex items-center justify-center h-64">
      <div className="w-8 h-8 border-2 border-brand-red border-t-transparent rounded-full animate-spin" />
    </div>
  );

  if (!summary) return <div className="card">Summary not found.</div>;

  return (
    <div className="max-w-3xl">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <Link href="/doctor-summary" className="btn-ghost"><ArrowLeft size={16} /></Link>
          <div>
            <h1 className="page-title">Doctor Visit Summary</h1>
            <p className="text-sm text-gray-400">
              {(summary as unknown as { family_members?: { full_name: string } }).family_members?.full_name} · {new Date(summary.created_at).toLocaleDateString("en-IN")}
            </p>
          </div>
        </div>
        <div className="flex gap-2 print:hidden">
          <button onClick={handleCopy} className="btn-ghost">
            <Copy size={16} /> Copy
          </button>
          <button onClick={handleDownloadPDF} className="btn-ghost">
            <Download size={16} /> PDF
          </button>
          <button onClick={handlePrint} className="btn-ghost">
            <Printer size={16} /> Print
          </button>
        </div>
      </div>

      <div className="card">
        <div className="prose max-w-none">
          <pre className="whitespace-pre-wrap font-sans text-gray-800 text-sm leading-relaxed">
            {summary.generated_summary}
          </pre>
        </div>
      </div>

      <div className="card mt-4 bg-gray-50 border-gray-200">
        <p className="text-xs text-gray-500">
          This summary was generated by AI based on the information you provided and is intended to help you communicate with your doctor. It is not a medical diagnosis or prescription. Please consult a registered medical practitioner.
        </p>
      </div>
    </div>
  );
}
